### ISSUE TITLE
Unable to edit Todo

### ISSUE THREAD

**Issue by josephting** [jerry54604/react-flux-exercise#1]
:open_mouth: Pro @jerry54604 at it again. :+1: 

But cannot edit todo :disappointed:

**Comment by jerry54604** [comment]
lol, this is just an introduction to flux 😮 
so complicated this thing :(

**Comment by josephting** [comment]
Pro people do pro thing. Sasuga @jerry54604

**Comment by jerry54604** [comment]
lol
I can't called pro when I don't understand this 😞

**Comment by josephting** [comment]
Don't understand still do most pro :clap:

**Comment by jerry54604** [comment]
lol just follow instruction copy n paste 😮

**Comment by josephting** [comment]
I just saw [this](https://github.com/facebook/flux/blob/master/examples/flux-todomvc/README.md). :laughing: 

Pro people follow pro instructions :open_mouth:

**Comment by jerry54604** [comment]
lol, not pro, just noobing around 😟
