### ISSUE TITLE
node_modules should not be pushed into repo

### ISSUE THREAD

**Issue by josephting** [jerry54604/react-flux-exercise#2]
`node_modules` should be installed using [npm](https://www.npmjs.com) (or maybe [yarn](https://yarnpkg.com)) after cloning to development or production environment.

Repository should be clean of other stuff that can be installed easily.

This might be a [good gitignore template](https://github.com/github/gitignore/blob/master/Node.gitignore) you can use for this project.

**Comment by jerry54604** [comment]
proseph 😮

**Comment by josephting** [comment]
I also just noobing around :worried:

**Comment by jerry54604** [comment]
no you are not 🤸‍♀️

**Comment by josephting** [comment]
What is that emoji!!!? :confused:

**Comment by jerry54604** [comment]
flipping lol

**Comment by josephting** [comment]
Yes, I'm not :woman_cartwheeling:

**Comment by jerry54604** [comment]
🤸‍♂️

**Comment by josephting** [comment]
Junk removed with d0845751c8d1dd87cf12c071fbd24296433241c0
Fixed with 1f558f90394cd4877bab13f68bd8fbe55ed7b6fc
